### ISSUE TITLE
The prediction is bad

### ISSUE THREAD

**Issue by LeoDarcy** [crs4/SliceNet#3]
I have tried to load and evaluate the images in Matterport following the README, but the prediction is not good. I wonder if  you share the wrong resnet50_m3d.pth by mistake. I use the image from "Matterport3D/1LXtFkjw3qL/pano_color/0b22fa63d0f54a529c525afbf2e8bb25.jpg" and here is the prediction:
![1_depth_pred](https://user-images.githubusercontent.com/28213850/141683758-237a7325-1dc6-4f36-9e29-087c1f034979.jpg)
n.

**Comment by giannipint** [comment]
Hi Leo, i've tried the image you mentioned, you just need to use the right mask. in this case is also more important since a larger part of the scene is an outdoor. next i'll upload a pytorch dataset loader to propely load image, mask and ground truth.
Here attached the prediction using the mask:
 
![Figure_0](https://user-images.githubusercontent.com/25104268/143847952-28c409c2-615d-4ee8-84aa-054f4b284eb2.png)
d
